<?php 
// writing statement in a file 
include('statement.php');
include('values.php');
include('fontnames.php');
//end of writing statement :


//if($_POST['check1']==5 ||  $_POST['checklogin1']==5  ||  $_POST['checklogin2']==5)
//{
$rand1=rand(1, 8);
$rand2=rand(9, 15);

?>
<!DOCTYPE html 
      PUBLIC "-//W3C//DTD HTML 4.01//EN"
      "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=New+Rocker' rel='stylesheet' type='text/css'>

 <link rel="icon" href="./favicon.ico" type="image/x-icon">
<title>
Cute Or Not
</title>
</head>



<style type="text/css">
.css_btn_class {
	font-size:16px;
	font-family:Arial;
	font-weight:normal;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	border:1px solid #dcdcdc;
	padding:9px 18px;
	text-decoration:none;
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	background:-ms-linear-gradient( top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #ededed), color-stop(100%, #dfdfdf) );
	background-color:#ededed;
	color:#777777;
	display:inline-block;
	text-shadow:1px 1px 0px #ffffff;
 	-webkit-box-shadow:inset 1px 1px 0px 0px #ffffff;
 	-moz-box-shadow:inset 1px 1px 0px 0px #ffffff;
 	box-shadow:inset 1px 1px 0px 0px #ffffff;
}.css_btn_class:hover {
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	background:-ms-linear-gradient( top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #dfdfdf), color-stop(100%, #ededed) );
	background-color:#dfdfdf;
}.css_btn_class:active {
	position:relative;
	top:1px;
}
/* This css button was generated by css-button-generator.com */
</style>


<style>
.btn {
	  background: #3498db;
		        background-image: -webkit-linear-gradient(top, #3498db, #2980b9);
			  background-image: -moz-linear-gradient(top, #3498db, #2980b9);
			    background-image: -ms-linear-gradient(top, #3498db, #2980b9);
			      background-image: -o-linear-gradient(top, #3498db, #2980b9);
			        background-image: linear-gradient(to bottom, #3498db, #2980b9);
				  -webkit-border-radius: 28;
				    -moz-border-radius: 28;
				      border-radius: 28px;
				        font-family: Arial;
					  color: #ffffff;
						   font-size: 20px;
						     padding: 10px 20px 10px 20px;
							        text-decoration: none;
}

.btn:hover {
	  background: #3cb0fd;
		        background-image: -webkit-linear-gradient(top, #3cb0fd, #3498db);
			  background-image: -moz-linear-gradient(top, #3cb0fd, #3498db);
			    background-image: -ms-linear-gradient(top, #3cb0fd, #3498db);
			      background-image: -o-linear-gradient(top, #3cb0fd, #3498db);
			        background-image: linear-gradient(to bottom, #3cb0fd, #3498db);
				  text-decoration: none;
}

body
{
background-image:url(bg.jpg);
}

table {
    border-collapse: collapse;
}

#head
{
border : 1px solid blue;
}
td {
    padding-top: .5em;
    padding-bottom: .5em;
}
</style>
</body>
<br>
<!-- HEADING -->
<div id="head">
<br >
<h1 style="font-family: 'New Rocker', cursive;"  align="center" style="position:relative; top:100px;">

Cute Or Not 
</h1>
</div>
<br>
<table align="center"  border="0"    cellpadding="15" >
<tr>
<!-- First Column -->
<td>
<?php include('fonts/'.$rand1.'.php') ?>
</td>


<td>
</td> 

<td>
</td> 


<td>
OR 
</td>

 

<td>
</td>
<br> 
<!-- Second  Column -->
<td>
<?php include('fonts/'.$rand2.'.php') ?>
</td>

</tr>	

<tr>
<!-- second  row -->
<td>
<table border="0">
<tr>
<td>
Dog Name: <b><?php echo $name[$rand1]; ?></b>
</td>
</tr>

<tr>
<td>
Current Rating : <b><?php echo $ratings[$rand1]; ?></b>
</td>
</tr>


<tr>
<td>
Users Rated : <b><?php echo $scores[$rand1]; ?></b>
</td>
</tr>

</table>

</td>


<td>
</td> 

<td>
</td> 


<td>
</td>

 

<td>
</td>
<br> 
<!-- Second  Column -->
<td>
<table border="0">
<tr>
<td>
Dog Name : <b><?php echo $name[intval($rand2)]; ?></b>
</td>
</tr>

<tr>
<td>
Current Rating : <b><?php echo $ratings[$rand2]; ?></b>
</td>
</tr>


<tr>
<td>
Users Rated : <b><?php echo $scores[$rand2]; ?></b>
</td>
</tr>

</table>

</td>

</tr>	

<!--4  New row -->

<tr>

<form name="form1"  action="login1.php" method="POST" >
<td>
<input type="hidden" name="checklogin1" value="5" ></input> 
<input type="hidden" name="statement" value=<?php echo $_POST['statement']?> ></input> 
<input class="btn" type="submit" name="1.php"  value="Vote" ></input>
<input type='hidden' name='redirect'  value='index2.php'></input>
<input type='hidden' name='file1'  value='<?php echo $rand1;?>'></input>
<input type='hidden' name='file2'  value='<?php echo $rand2;?>'></input>
</td>
</form>

<td>
</td>

<td>
</td>


<td>
</td>



<td>
</td>
<!-- Second  Column -->
<form name="form1"  action="login2.php" method="POST" >
<td>
<input type="hidden" name="checklogin2" value="5"></input> 
<input type="hidden" name="statement" value=<?php echo $_POST['statement']?> ></input> 
<input class="btn" type="submit" name="1.php"  value="Vote" ></input>
<input type='hidden' name='redirect'  value='index2.php'></input>
<input type='hidden' name='file1'  value='<?php echo $rand1;?>'></input>
<input type='hidden' name='file2'  value='<?php echo $rand2;?>'></input>
</td>
</form>

</tr>
 

<!-- end -->
</table>
<br>
<br>

<form action="final.php" method="POST">
<input type='hidden' name='final'  value='9'></input>
<input class="css_btn_class" style="position:relative; left:550px"  type="submit" name="1.php"  value="END" ></input>
</form>	

</body>
</html>

<?php
//}

//else
//{
//header('Location:./welcome.php');

//}
?>

